module.exports = {
  appId: "com.baobao2333.wireframe-studio",
  productName: "Wireframe Studio",
  electronVersion: "44.3.0",
  directories: { app: "build/desktop-app", buildResources: "assets", output: "release" },
  asar: true,
  npmRebuild: false,
  files: [
    "desktop/*.{mjs,cjs,json}",
    "desktop/update-public-key.pem",
    "server/vision-schema.mjs",
    "renderer/**/*",
    "package.json",
    "!**/.release-secrets/**",
    "!**/*private-key*",
    "!**/*private_key*",
    "!renderer/ocr/**",
    "!renderer/**/*.{pem,key,p12,pfx}",
    "!node_modules/**/*.{pem,key,p12,pfx}",
  ],
  extraResources: [
    { from: "build/THIRD-PARTY-NOTICES.txt", to: "THIRD-PARTY-NOTICES.txt" },
    { from: "public/ocr", to: "ocr", filter: ["**/*"] },
    { from: "server/vision-instructions.txt", to: "vision-instructions.txt" },
    { from: "assets/app.ico", to: "app.ico" },
  ],
  win: { target: [{ target: "nsis", arch: ["x64"] }], icon: "app.ico" },
  nsis: {
    oneClick: false,
    perMachine: false,
    selectPerMachineByDefault: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: true,
    packElevateHelper: false,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: "Wireframe Studio",
    deleteAppDataOnUninstall: false,
    installerIcon: "app.ico",
    uninstallerIcon: "app.ico",
    include: "assets/installer.nsh",
    artifactName: "Wireframe-Studio-Setup-${version}-x64.exe",
  },
  fileAssociations: [{ ext: "wireframe", name: "WireframeStudio.Project", description: "Wireframe Studio Project", icon: "app.ico" }],
  publish: [{ provider: "github", owner: "baobao2333", repo: "wireframe-studio" }],
};
