const string={type:"string"};const number={type:"number"};
const enumOf=values=>({type:"string",enum:values});
const object=properties=>({type:"object",properties,required:Object.keys(properties),additionalProperties:false});
const array=items=>({type:"array",items});
export const visionSchema=object({title:string,summary:string,width:number,height:number,background:{type:"string",description:"Visible canvas background color from the screenshot, as six-digit hex or none. Do not default to white. Use a representative visible color for a gradient or illustration and explain that approximation in summary."},nodes:array(object({
  id:string,parentId:{type:["string","null"],description:"Null for top-level nodes, otherwise the EXACT id of an existing frame node. Only frame can be a parent. Never self-reference or create cycles."},type:enumOf(["text","richtext","button","input","select","image","frame","line","checkbox","radio","switch","tag","avatar","icon","progress","tabs","table","list"]),name:string,x:{type:"number",minimum:-10000,maximum:20000},y:{type:"number",minimum:-10000,maximum:20000},w:{type:"number",minimum:4,maximum:6000},h:{type:"number",minimum:2,maximum:6000},text:{type:"string",description:"Literal visible text for text-bearing components. Only for type=icon: one or a few Unicode symbols/emoji representing an unambiguous visible simple icon, or an empty string to use the icon enum. Preserve variation selectors, ZWJ sequences and any literal visible symbols exactly. No HTML, image URL, invented label or inferred action. Explain semantic substitutions in note."},fontSize:{type:"number",minimum:8,maximum:160},fontWeight:enumOf(["400","500","600","700"]),align:enumOf(["left","center","right"]),lineHeight:{type:"number",minimum:1,maximum:3,description:"Unitless multiplier, e.g. 1.5. Never pixels."},color:string,fill:string,stroke:string,radius:{type:"number",minimum:0,maximum:3000},priority:enumOf(["primary","secondary","tertiary"]),note:string,confidence:{type:"number",minimum:0,maximum:100,description:"Percentage confidence, e.g. 95. Not 0..1."},
  strokeWidth:{type:"number",minimum:0,maximum:12,description:"Visible rectangular/component border width in target CSS pixels. Use 0 when stroke is none. Never put a glyph outline here."},textStroke:{type:"string",description:"Outline color around the actual text glyphs, as six-digit hex or none. Separate from the component border stroke. Use none when no glyph outline is visible."},textStrokeWidth:{type:"number",minimum:0,maximum:12,description:"Visible glyph outline width in target CSS pixels; 0 if textStroke is none."},
  runs:array(object({text:string,fontSize:{type:"number",minimum:8,maximum:160},fontWeight:enumOf(["400","500","600","700"]),color:string,italic:{type:"boolean"},underline:{type:"boolean"}})),items:array(string),rows:array(array(string)),value:{type:"number",minimum:0,maximum:1,description:"Control state or progress fraction in 0..1, never a percentage number or visible numeric label. For progress use 0.78 for 78%. For checkbox/radio/switch use 0 for off and 1 for on. For all other types use 0 and keep any visible number in text."},icon:{...enumOf(["search","home","user","bell","settings","menu","chevron-right","plus","star","heart","check","close"]),description:"Existing line-icon library. Used only for type=icon with text empty; ignored when text contains a Unicode symbol. Choose only a visually supported match, not an assumed function."}
}))});
