import assert from "node:assert/strict";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { unzipSync, strFromU8 } from "fflate";
import sharp from "sharp";
import ts from "typescript";
import { validateStudioFile } from "../lib/grapes-export.ts";

const input = process.argv[2];
assert.ok(input,"Pass the ZIP file exported through the editor UI.");
const files = unzipSync(await readFile(input));
const expected = ["project.json","design-spec.json","index.html","Wireframe.tsx","handoff.md","wireframe.svg","wireframe.png"];
assert.deepEqual(Object.keys(files).sort(),expected.toSorted());
const project = validateStudioFile(JSON.parse(strFromU8(files["project.json"])));
const spec = JSON.parse(strFromU8(files["design-spec.json"]));
assert.equal(spec.canvas.width,project.meta.width);
assert.equal(spec.canvas.reference,undefined);
let nodes = 0,richtext = 0,styled = 0;
const visit = node => {
  nodes++;
  if(node.type === "richtext") richtext++;
  if(node.bounds?.width > 0 && node.typography) styled++;
  node.children.forEach(visit);
};
spec.components.forEach(visit);
assert.ok(styled > 0,"Exported components must have measured styles and bounds.");
const html = strFromU8(files["index.html"]);
assert.equal((html.match(/<body\b/g)||[]).length,1);
const tsx = strFromU8(files["Wireframe.tsx"]);
assert.match(tsx,/<main\b/);
assert.doesNotMatch(tsx,/<body\b/);
const result = ts.transpileModule(tsx,{fileName:"Wireframe.tsx",compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});
assert.equal(result.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error).length,0);
const png = sharp(files["wireframe.png"]);
const info = await png.metadata(),stats = await png.stats();
assert.equal(info.width,project.meta.width*2);
assert.equal(info.height,project.meta.height*2);
assert.ok(stats.channels.slice(0,3).some(c=>c.stdev>10),"PNG must not be blank.");
const output = resolve(import.meta.dirname,"../work/export-qa");
await mkdir(output,{recursive:true});
for(const name of expected) await writeFile(resolve(output,name),files[name]);
console.log(JSON.stringify({passed:true,members:expected.length,nodes,richtext,measured:styled,png:{width:info.width,height:info.height},output},null,2));
